### ISSUE TITLE
Not working with latest version of gmw multi-site

### ISSUE THREAD

**Issue by beatelite** [yaronguez/gmw-taxonomy#1]
I cloned this and installed it network-wide on a multisite install but no luck. Nothing showed up under gmw settings even though i see it's active. 

wp 4.2.2
gmw 2.6.4
Mutlisite setup

**Comment by yaronguez** [comment]
Hmm I have the same version of WP and GMW and it's working fine for me. Unfortunately I don't have a multisite install handy to test it out on. Have you tried contacting Eyal directly?  He's added my Taxonomy Locator to his site at https://geomywp.com/add-ons/taxonomy-locator/ so he might know more about issues with GMW Addons and multi-site. Let me know what you find!

**Comment by Fitoussi** [comment]
Hi Beatelite,
I haven't tested GEO my WP Taxonomy on a multisite yet but when I first installed on a single site installation I experienced the same issue you describe. For me the issue was the name of the folder which was gmw-taxonomy-master. After changing it to gmw-taxonomy everything was working. Please try that and see if that the case for you as well. Otherwise, I will look into it again.
