### ISSUE TITLE
Taxonomies tab not displaying

### ISSUE THREAD

**Issue by petebocken** [yaronguez/gmw-taxonomy#4]
I installed this plugin and I do not see the "Taxonomies" tab in the GeomyWP Settings.

**Comment by novuu** [comment]
same here...

**Comment by yaronguez** [comment]
So strange. Really sorry you guys are having trouble and wish I had the
time to debug this with you. I still have no problems running this plugin
on my sites.

**Comment by djundco** [comment]
and same here

**Comment by Fitoussi** [comment]
Hi,
One thing to check is that the folder of the plugin named gmw-taxonomy and not gmw-taxonomy-master which is the default name when downloading the zip file from GitHub. You should then be able to enable the add-on from GEO my WP add-ons page ( dashboard -> GEO my WP -> Add-ons ).

Otherwise, I am very close to release the first beta of GEO my WP 3.0. This is a major release I have been working on for almost 2 years. I had to pause the development on it for a few months and only recently got back to it. Once I release version 3.0 I will need to update all the extensions, including the taxonomy extension ( with the permission and, perhaps, the help of @yaronguez ), to be compatible with it. Hopefully everything will work well after the updates.

**Comment by bsmolyansky** [comment]
Hello.  I too cannot see the tab.  Any progress here?

**Comment by yaronguez** [comment]
Not from me, unfortunately. I developed this addon over a year ago for a client and it continues to work perfectly on their site. I haven't been able to reproduce the problem and don't have the bandwidth to dive deeper but anyone else is welcome to give it a shot. I'm happy to accept any pull requests.

**Comment by Fitoussi** [comment]
You can try and fix this issue ( a temporary fix ) by removing the check of GEO my WP activation. To do so, open the file gmw-taxnomy/gmw-taxonomy.php and mark out ( or remove ) lines 56,57 and 58, which should be:

`if ( !GEO_my_WP::gmw_check_addon( 'taxonomies' ) ) {`
     ` return;`
  `}`

I hope this helps until we get this fixed after the official release of GEO my WP 3.0.

**Comment by bryansayler** [comment]
Commenting out lines 56-58 as described in @Fitoussi comment on Oct 5 worked for me!

**Comment by mitchgould** [comment]
That gives me the tab in GMW settings, but when I select the taxonomies to add to, the location information does not show up.

**Comment by mitchgould** [comment]
So, there is a post from almost 2 years ago that says version 3.0 is almost ready, but code still at 1.0.14.  Main page says plugin is not compatible with GMW 3.0+.

Is there a new version coming?  The fix above got my tab showing in settings, but doesn't save updates properly, so no location fields on taxonomies.
